version: "3"
services:
  car_management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./car_management:/app
    command: python manage.py runserver 0.0.0.0:8000
